id: Microsoft_365_Defender-Test
version: -1
name: Microsoft_365_Defender-Test
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: ecbd1aea-3116-453e-8e0e-6114c0fdff77
    type: start
    task:
      id: ecbd1aea-3116-453e-8e0e-6114c0fdff77
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "6"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 970
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "6":
    id: "6"
    taskid: 7768faec-5dfa-4d44-8592-e257ba10ce56
    type: regular
    task:
      id: 7768faec-5dfa-4d44-8592-e257ba10ce56
      version: -1
      name: microsoft-365-defender-incidents-list
      script: '|||microsoft-365-defender-incidents-list'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "7"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1200
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "7":
    id: "7"
    taskid: e65579a5-8d38-4af4-8890-764ee4fcdc82
    type: condition
    task:
      id: e65579a5-8d38-4af4-8890-764ee4fcdc82
      version: -1
      name: Verify Outputs
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "8"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: Microsoft365Defender.Incident.incidentId
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: Microsoft365Defender.Incident.redirectIncidentId
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: Microsoft365Defender.Incident.incidentName
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: Microsoft365Defender.Incident.createdTime
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: Microsoft365Defender.Incident.lastUpdateTime
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: Microsoft365Defender.Incident.assignedTo
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: Microsoft365Defender.Incident.classification
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: Microsoft365Defender.Incident.determination
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: Microsoft365Defender.Incident.status
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: Microsoft365Defender.Incident.severity
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: Microsoft365Defender.Incident.alerts
            iscontext: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1400
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "8":
    id: "8"
    taskid: 35130915-473c-4baf-8108-dba0d3cf680a
    type: regular
    task:
      id: 35130915-473c-4baf-8108-dba0d3cf680a
      version: -1
      name: microsoft-365-defender-incident-update
      script: '|||microsoft-365-defender-incident-update'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "9"
    scriptarguments:
      id:
        simple: ${Microsoft365Defender.Incident.incidentId}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1600
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "9":
    id: "9"
    taskid: d004e289-ee92-4ecd-8abe-025738dc1ded
    type: condition
    task:
      id: d004e289-ee92-4ecd-8abe-025738dc1ded
      version: -1
      name: Verify Outputs
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "10"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: Microsoft365Defender.Incident.incidentId
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: Microsoft365Defender.Incident.redirectIncidentId
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: Microsoft365Defender.Incident.incidentName
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: Microsoft365Defender.Incident.createdTime
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: Microsoft365Defender.Incident.lastUpdateTime
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: Microsoft365Defender.Incident.assignedTo
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: Microsoft365Defender.Incident.classification
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: Microsoft365Defender.Incident.determination
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: Microsoft365Defender.Incident.status
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: Microsoft365Defender.Incident.severity
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: Microsoft365Defender.Incident.alerts
            iscontext: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1800
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "10":
    id: "10"
    taskid: 74e0e32c-65cc-4167-8715-ad7786b96699
    type: regular
    task:
      id: 74e0e32c-65cc-4167-8715-ad7786b96699
      version: -1
      name: microsoft-365-defender-advanced-hunting
      script: '|||microsoft-365-defender-advanced-hunting'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "11"
    scriptarguments:
      query:
        simple: AlertInfo
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2000
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "11":
    id: "11"
    taskid: 9ef22412-9f99-4d4f-8261-fbd9bc2c99b7
    type: condition
    task:
      id: 9ef22412-9f99-4d4f-8261-fbd9bc2c99b7
      version: -1
      name: Verify Outputs
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "12"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: Microsoft365Defender.Hunt.query
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: Microsoft365Defender.Hunt.results.
            iscontext: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2200
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "12":
    id: "12"
    taskid: 49c2e090-213d-411f-8d04-cea79deb7a9d
    type: title
    task:
      id: 49c2e090-213d-411f-8d04-cea79deb7a9d
      version: -1
      name: Test Done
      type: title
      iscommand: false
      brand: ""
      description: ''
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2400
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1495,
        "width": 380,
        "x": 50,
        "y": 970
      }
    }
  }
inputs: []
outputs: []
fromversion: 5.5.0
description: Test playbook
